#!/usr/bin/env bash
# Display:
#  The content of the current directory
#  In a list format
#  Where only the part of the name after the first dash is displayed

for _ in *; do
    echo '$_' | cut -d '-' -f 2

done
